# Generated by Django 3.2.12 on 2026-02-26 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='manufacturers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='orderstatuses',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pickuppoints',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productsinorders',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='producttypes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='providers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='units',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
    ]
